/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author rodri
 */
public class MenuAdm extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdm
     */
    public MenuAdm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mensajeUser = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        botonGestionarRservas = new javax.swing.JButton();
        botonGestionarPersonal1 = new javax.swing.JButton();
        botonVerIngresos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Menu Administrador");

        mensajeUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/recepticon.jpg"))); // NOI18N

        salir.setText("Cerrar sesión");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        botonGestionarRservas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botonGestionarRservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/descarga.png"))); // NOI18N
        botonGestionarRservas.setText("Gestionar Reservas");
        botonGestionarRservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGestionarRservasActionPerformed(evt);
            }
        });

        botonGestionarPersonal1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botonGestionarPersonal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/img1.jpg"))); // NOI18N
        botonGestionarPersonal1.setText("Gestionar Personal");
        botonGestionarPersonal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGestionarPersonal1ActionPerformed(evt);
            }
        });

        botonVerIngresos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botonVerIngresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/line-icon-for-money-vector.jpg"))); // NOI18N
        botonVerIngresos.setText("Visualizar Ingresos");
        botonVerIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerIngresosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mensajeUser))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(387, 387, 387)
                        .addComponent(salir)))
                .addContainerGap(197, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonGestionarPersonal1)
                    .addComponent(botonVerIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonGestionarRservas, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(288, 288, 288))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mensajeUser)
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addComponent(botonGestionarPersonal1)
                .addGap(18, 18, 18)
                .addComponent(botonGestionarRservas, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonVerIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(salir)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salirActionPerformed

    private void botonGestionarRservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestionarRservasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGestionarRservasActionPerformed

    private void botonGestionarPersonal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestionarPersonal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGestionarPersonal1ActionPerformed

    private void botonVerIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerIngresosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonVerIngresosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdm().setVisible(true);
            }
        });
    }

    public javax.swing.JLabel getMenajeUser() {
        return mensajeUser;
    }

    public javax.swing.JButton getBotonvolver() {
        return salir;
    }

    public javax.swing.JButton getBotonGestionarPersonal() {
        return botonGestionarPersonal1;
    }

    public javax.swing.JButton getBotonGestionarReservas() {
        return botonGestionarRservas;
    }

    public javax.swing.JButton getBotonVerIngresos() {
        return botonVerIngresos;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGestionarPersonal1;
    private javax.swing.JButton botonGestionarRservas;
    private javax.swing.JButton botonVerIngresos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel mensajeUser;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
